# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20161212_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontuser',
            name='headImg',
            field=models.URLField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
