# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('front', '0003_frontuser_headimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commodityName', models.CharField(max_length=30)),
                ('commodityDes', models.TextField()),
                ('commodityImg', models.URLField(blank=True, max_length=100)),
                ('commodityStock', models.IntegerField()),
                ('commodityPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commodityCtime', models.DateField(auto_now_add=True)),
                ('commodityPoints', models.IntegerField()),
                ('commondityCate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.CategoryModel')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartCtime', models.DateField(auto_now_add=True)),
                ('buyNum', models.IntegerField(default=1)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Commodity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.FrontUser')),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderSerial', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sendStatus', models.BooleanField(default=False)),
                ('reveiceStatus', models.BooleanField(default=False)),
                ('buyTime', models.DateTimeField(auto_now_add=True)),
                ('orderPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Commodity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.FrontUser')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='commondityTag',
            field=models.ManyToManyField(blank=True, to='backstage.TagModel'),
        ),
    ]
