# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodityName', models.CharField(max_length=30)),
                ('commodityDes', models.TextField()),
                ('commodityImg', models.URLField()),
                ('commodityStock', models.IntegerField()),
                ('commodityPrice', models.IntegerField()),
                ('commodityCtime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
