# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commodityImg',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
