# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0002_auto_20161210_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='id',
        ),
        migrations.AddField(
            model_name='commodity',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='commodity',
            name='commondityCate',
            field=models.ForeignKey(default=1993, on_delete=django.db.models.deletion.CASCADE, to='backstage.CategoryModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodity',
            name='commondityTag',
            field=models.ManyToManyField(null=True, to='backstage.TagModel'),
        ),
    ]
