# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0004_auto_20161211_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commondityTag',
            field=models.ManyToManyField(blank=True, to='backstage.TagModel'),
        ),
    ]
