# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
        ('backstage', '0005_auto_20161211_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartCtime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='commodityPoints',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodityPrice',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Commodity'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.FrontUser'),
        ),
    ]
